version: "3.4"  # Use a version that is supported by your Docker Compose CLI

services:
  frontend:
    build:
      context: ./mahza-lms-frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      NODE_ENV: development

  